version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: site-set-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: site-set
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local